name: Deploy to Production

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    environment:
      name: "development"
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - name: serverless deploy
        uses: serverless/github-action@v3
        with:
          args: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SMTP_ENDPOINT: ${{ secrets.AWS_SMTP_ENDPOINT }}
          AWS_SMTP_USER: ${{ secrets.AWS_SMTP_USER }}
          AWS_SMTP_PASSWORD: ${{ secrets.AWS_SMTP_PASSWORD }}